### ISSUE TITLE
Route [filament.admin.resources.projects.edit] not defined.

### ISSUE THREAD

**Issue by tonypartridge** [timwassenburg/filament-timesheets#2]
After adding a timesheet we get:

Route [filament.admin.resources.projects.edit] not defined.

**Comment by tonypartridge** [comment]
resolved with 1.0.1

**Comment by tonypartridge** [comment]
I was just going to do a PR but see you have done one already :-)

**Comment by timwassenburg** [comment]
Hi Tony, thanks for opening the issue. Sorry, I forgot to reply that I indeed made a fix for it. It was a bit busy last couple of days. I'll check the other issues as soon as I can.
